parameters:
    netgen.ezforms.form.data_mapper.create_content.class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\CreateContentMapper
    netgen.ezforms.form.type.create_content.class: Netgen\Bundle\EzFormsBundle\Form\Type\CreateContentType

    netgen.ezforms.form.data_mapper.create_user.class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\CreateUserMapper
    netgen.ezforms.form.type.create_user.class: Netgen\Bundle\EzFormsBundle\Form\Type\CreateUserType

    netgen.ezforms.form.data_mapper.update_content.class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\UpdateContentMapper
    netgen.ezforms.form.type.update_content.class: Netgen\Bundle\EzFormsBundle\Form\Type\UpdateContentType

    netgen.ezforms.form.data_mapper.update_user.class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\UpdateUserMapper
    netgen.ezforms.form.type.update_user.class: Netgen\Bundle\EzFormsBundle\Form\Type\UpdateUserType

    netgen.ezforms.form.url_type.class: Netgen\Bundle\EzFormsBundle\Form\Type\UrlType

    netgen.ezforms.form.map_type.class: Netgen\Bundle\EzFormsBundle\Form\Type\MapType

    netgen.ezforms.form.data_mapper.info_collection.class: Netgen\Bundle\EzFormsBundle\Form\DataMapper\InformationCollectionMapper
    netgen.ezforms.form.type.info_collection.class: Netgen\Bundle\EzFormsBundle\Form\Type\InformationCollectionType

    netgen.ezforms.form.type.xml_text.class: Netgen\Bundle\EzFormsBundle\Form\Type\XmlTextType

services:
    netgen.ezforms.form.data_mapper.create_content:
        class: "%netgen.ezforms.form.data_mapper.create_content.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.create_content:
        class: "%netgen.ezforms.form.type.create_content.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.create_content"
        tags:
            - {name: form.type, alias: ezforms_create_content}

    netgen.ezforms.form.data_mapper.create_user:
        class: "%netgen.ezforms.form.data_mapper.create_user.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.create_user:
        class: "%netgen.ezforms.form.type.create_user.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.create_user"
        tags:
            - {name: form.type, alias: ezforms_create_user}

    netgen.ezforms.form.data_mapper.update_content:
        class: "%netgen.ezforms.form.data_mapper.update_content.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.update_content:
        class: "%netgen.ezforms.form.type.update_content.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.update_content"
        tags:
            - {name: form.type, alias: ezforms_update_content}

    netgen.ezforms.form.data_mapper.update_user:
        class: "%netgen.ezforms.form.data_mapper.update_user.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.update_user:
        class: "%netgen.ezforms.form.type.update_user.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.update_user"
        tags:
            - {name: form.type, alias: ezforms_update_user}

    netgen.ezforms.form.url_type:
        class: "%netgen.ezforms.form.url_type.class%"
        tags:
            - {name: form.type, alias: ezforms_url}

    netgen.ezforms.form.map_type:
        class: "%netgen.ezforms.form.map_type.class%"
        tags:
            - {name: form.type, alias: ezforms_map}

    netgen.ezforms.form.data_mapper.info_collection:
        class: "%netgen.ezforms.form.data_mapper.info_collection.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"

    netgen.ezforms.form.type.info_collection:
        class: "%netgen.ezforms.form.type.info_collection.class%"
        arguments:
            - "@netgen.ezforms.form.fieldtype_handler_registry"
            - "@netgen.ezforms.form.data_mapper.info_collection"
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - {name: form.type, alias: ezforms_information_collection}

    netgen.ezforms.form.type.xml_text:
        class: '%netgen.ezforms.form.type.xml_text.class%'
        tags:
            - { name: form.type, alias: ezforms_xml }
