parameters:
    netgen.ezforms.form.fieldtype_handler.ezimage.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Image
    netgen.ezforms.form.fieldtype_handler.ezstring.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\TextLine
    netgen.ezforms.form.fieldtype_handler.eztext.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\TextBlock
    netgen.ezforms.form.fieldtype_handler.ezuser.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\User
    netgen.ezforms.form.fieldtype_handler.ezemail.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Email
    netgen.ezforms.form.fieldtype_handler.ezselection.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Selection
    netgen.ezforms.form.fieldtype_handler.ezboolean.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Checkbox
    netgen.ezforms.form.fieldtype_handler.ezdate.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Date
    netgen.ezforms.form.fieldtype_handler.ezdatetime.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\DateAndTime
    netgen.ezforms.form.fieldtype_handler.ezinteger.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\IntegerHandler
    netgen.ezforms.form.fieldtype_handler.ezfloat.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\FloatHandler
    netgen.ezforms.form.fieldtype_handler.ezurl.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Url
    netgen.ezforms.form.fieldtype_handler.ezcountry.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Country
    netgen.ezforms.form.fieldtype_handler.eztime.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Time
    netgen.ezforms.form.fieldtype_handler.ezisbn.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Isbn
    netgen.ezforms.form.fieldtype_handler.ezbinaryfile.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\BinaryFile
    netgen.ezforms.form.fieldtype_handler.ezgmaplocation.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\MapLocation
    netgen.ezforms.form.fieldtype_handler.ezobjectrelation.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Relation
    netgen.ezforms.form.fieldtype_handler.ezxml.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\XmlText
services:
    netgen.ezforms.form.fieldtype_handler.ezimage:
        class: "%netgen.ezforms.form.fieldtype_handler.ezimage.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezimage}

    netgen.ezforms.form.fieldtype_handler.ezstring:
        class: "%netgen.ezforms.form.fieldtype_handler.ezstring.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezstring}

    netgen.ezforms.form.fieldtype_handler.eztext:
        class: "%netgen.ezforms.form.fieldtype_handler.eztext.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: eztext}

    netgen.ezforms.form.fieldtype_handler.ezuser:
        class: "%netgen.ezforms.form.fieldtype_handler.ezuser.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezuser}

    netgen.ezforms.form.fieldtype_handler.ezemail:
        class: "%netgen.ezforms.form.fieldtype_handler.ezemail.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezemail}

    netgen.ezforms.form.fieldtype_handler.ezselection:
        class: "%netgen.ezforms.form.fieldtype_handler.ezselection.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezselection}

    netgen.ezforms.form.fieldtype_handler.ezboolean:
        class: "%netgen.ezforms.form.fieldtype_handler.ezboolean.class%"
        arguments: [ "@ezpublish.field_helper" ]
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezboolean}

    netgen.ezforms.form.fieldtype_handler.ezdate:
        class: "%netgen.ezforms.form.fieldtype_handler.ezdate.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezdate}

    netgen.ezforms.form.fieldtype_handler.ezdatetime:
        class: "%netgen.ezforms.form.fieldtype_handler.ezdatetime.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezdatetime}

    netgen.ezforms.form.fieldtype_handler.ezinteger:
        class: "%netgen.ezforms.form.fieldtype_handler.ezinteger.class%"
        arguments: [ "@ezpublish.field_helper" ]
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezinteger}

    netgen.ezforms.form.fieldtype_handler.ezfloat:
        class: "%netgen.ezforms.form.fieldtype_handler.ezfloat.class%"
        arguments: [ "@ezpublish.field_helper" ]
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezfloat}

    netgen.ezforms.form.fieldtype_handler.ezurl:
        class: "%netgen.ezforms.form.fieldtype_handler.ezurl.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezurl}

    netgen.ezforms.form.fieldtype_handler.ezcountry:
        class: "%netgen.ezforms.form.fieldtype_handler.ezcountry.class%"
        arguments:
            - "%ezpublish.fieldType.ezcountry.data%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezcountry}

    netgen.ezforms.form.fieldtype_handler.eztime:
        class: "%netgen.ezforms.form.fieldtype_handler.eztime.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: eztime}

    netgen.ezforms.form.fieldtype_handler.ezisbn:
        class: "%netgen.ezforms.form.fieldtype_handler.ezisbn.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezisbn}

    netgen.ezforms.form.fieldtype_handler.ezbinaryfile:
        class: "%netgen.ezforms.form.fieldtype_handler.ezbinaryfile.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezbinaryfile}

    netgen.ezforms.form.fieldtype_handler.ezgmaplocation:
        class: "%netgen.ezforms.form.fieldtype_handler.ezgmaplocation.class%"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezgmaplocation}

    netgen.ezforms.form.fieldtype_handler.ezobjectrelation:
        class: "%netgen.ezforms.form.fieldtype_handler.ezobjectrelation.class%"
        arguments:
          - "@ezpublish.api.repository"
          - "@ezpublish.translation_helper"
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezobjectrelation}

    netgen.ezforms.form.fieldtype_handler.ezxml:
        class: '%netgen.ezforms.form.fieldtype_handler.ezxml.class%'
        arguments:
            - '@ezpublish.fieldType.ezxmltext'
        tags:
            - { name: netgen.ezforms.form.fieldtype_handler, alias: ezxmltext }